Kiosk/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
# from Kiosk import settings
# from django.templatetags.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('kiosk/', include('kioskapp.urls')),
    path('', RedirectView.as_view(url='kiosk/', permanent=True)),
    path('accounts/', include('django.contrib.auth.urls')),
]

#+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

kioskapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),

    # path('items/', views.item_list_view, name='items'),
    path('items/', views.ItemsListView.as_view(), name='items'),
    # path('item/<int:primary_key>', views.item_detail_view, name='item-detail'),
    path('item/<int:pk>', views.ItemDetailView.as_view(), name='item-detail'),
    path('suppliers/', views.SuppliersListView.as_view(), name='suppliers'),
    path('supplier/<int:pk>', views.SupplierDetailView.as_view(), name='supplier-detail'),
    path('categories/', views.CategoriesListView.as_view(), name='categories'),
    path('category/<int:pk>', views.CategoryDetailView.as_view(), name='category-detail'),
    path('receiveditems/', views.ReceivedItemsListView.as_view(), name='receiveditems'),
    path('receiveditem/<int:pk>', views.ReceivedItemDetailView.as_view(), name='received_item-detail'),
    path('solditems/', views.SoldItemsListView.as_view(), name='solditems'),
    path('solditem/<int:pk>', views.SoldItemDetailView.as_view(), name='sold_item-detail'),
    # path('solditem/<int:pk>', views.sold_item_view, name='sold_item_detail'),
    
    path('item/create/', views.ItemCreate.as_view(), name='item_create'),
    path('item/<int:pk>/update/', views.ItemUpdate.as_view(), name='item_update'),
    path('item/<int:pk>/delete/', views.ItemDelete.as_view(), name='item_delete'),
]

kioskapp/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse

# Create your models here.
class User_type(models.Model):
    timestamp = models.DateTimeField(default = timezone.now(), editable=False)
    # Make permission class instead
    # PERMISSIONS = (
    #     ('0', 'No access'),
    #     ('1', 'Read'),
    #     ('2', 'Read/Write/Update'),
    #     ('3', 'All access'),
    # )
    # permission = models.ModelMul.CharField(
    #     max_length=1, 
    #     choices=PERMISSIONS,
    #     default='0',
    #     help_text='Select user permission',
    # )
    user_type_name = models.CharField(max_length=15, help_text='Enter user type')

    class Meta:
        verbose_name_plural = "User types"
    
    def __str__(self):
        return self.user_type_name
    
    def get_absolute_url(self):
        return reverse('user_type-detail', args=[str(self.id)])

class User(models.Model):
    timestamp = models.DateTimeField(default = timezone.now(), editable=False)
    fullname = models.CharField('Full name', max_length=50)
    email = models.EmailField()
    password = models.CharField(max_length=50)
    #raw_password = models.CharField(max_length=50)
    #password = make_password(raw_password)
    mobile = models.CharField(max_length=15)
    user_type = models.ManyToManyField(User_type, help_text='Select user type')

    def __str__(self):
        return self.fullname
    
    def get_absolute_url(self):
        return reverse('user-detail', args=[str(self.id)])

class Category(models.Model):
    timestamp = models.DateTimeField(default = timezone.now(), editable=False)
    user = models.ForeignKey(User, on_delete = models.SET_NULL, null=True)
    category_name = models.CharField(max_length=15, help_text='Enter category name')
    
    class Meta:
        verbose_name_plural = "categories"

    def __str__(self):
        return self.category_name
    
    def get_absolute_url(self):
        return reverse('category-detail', args=[str(self.id)])

class Item(models.Model):
    #timestamp = models.DateTimeField(auto_now = True)
    timestamp = models.DateTimeField(default=timezone.now(), editable=False)
    user = models.ForeignKey(User, on_delete = models.SET_NULL, null=True)
    barcode = models.CharField('Bar code', max_length=10, help_text='Enter barcode')
    item_name = models.CharField(max_length=25, help_text='Enter item name')
    category = models.ForeignKey(Category, on_delete = models.SET_NULL, null=True, help_text='Select category')
    brandname = models.CharField('Brand name', max_length=25, help_text='Enter brand name')
    modelname = models.CharField('Model name', max_length=25, help_text='Enter model name')
    item_description = models.TextField(max_length=50, help_text='Enter item description')
    # item_batch_info = models.ForeignKey('Item_batch', on_delete=models.SET_NULL, null=True)
    supplier = models.ForeignKey('Supplier', on_delete=models.SET_NULL, null=True, help_text='Select supplier')
    sellingprice = models.FloatField('Selling price', help_text='Enter selling price')

    def __str__(self):
        return self.item_name
    
    def get_absolute_url(self):
        return reverse('item-detail', args=[str(self.id)])

class Item_properties(models.Model):
    # Vare_egenskaber_id = models.AutoField(primary_key = True)
    timestamp = models.DateTimeField(default = timezone.now(), editable=False)
    user = models.ForeignKey(User, on_delete = models.SET_NULL, null=True)
    item = models.ForeignKey(Item, on_delete = models.SET_NULL, null=True, help_text='Select item')
    color = models.CharField(max_length = 25, help_text='Enter item color')
    size = models.CharField(max_length = 20, help_text='Enter item size')
    weight = models.FloatField(help_text='Enter item weight')

    class Meta:
        verbose_name_plural = "Item properties"

    def __str__(self):
        return self.color

    def get_absolute_url(self):
        return reverse('item_properties-detail', args=[str(self.id)])
 

class Item_batch(models.Model):
    # Vare_batch_id = models.AutoField(primary_key = True)
    timestamp = models.DateTimeField(default = timezone.now(), editable=False)
    user = models.ForeignKey(User, on_delete = models.SET_NULL, null=True)
    item = models.ForeignKey(Item, on_delete = models.SET_NULL, null=True, help_text='Select item')
    item_batch_code = models.CharField(max_length = 15, help_text='Enter batch code')
    manufacture_date = models.DateField(help_text='Enter manufacture date')
    expiry_date = models.DateField(help_text='Enter expiry date')
    
    class Meta:
        verbose_name_plural = "Item batches"

    def __str__(self):
        return self.item_batch_code
    
    def get_absolute_url(self):
        return reverse('item_batch-detail', args=[str(self.id)])

class Supplier(models.Model):
    # supplier_id = models.AutoField(primary_key = True)
    timestamp = models.DateTimeField(default = timezone.now(), editable=False)
    user = models.ForeignKey(User, on_delete = models.SET_NULL, null=True)
    #item_info = models.ForeignKey(Item, on_delete = models.SET_NULL, null=True)
    supplier_name = models.CharField(max_length = 40, help_text='Enter supplier name')
    
    def __str__(self):
        return self.supplier_name
    
    def get_absolute_url(self):
        return reverse('supplier-detail', args=[str(self.id)])

class Received_item(models.Model):
    # modtaget_id = models.AutoField(primary_key = True)
    timestamp = models.DateTimeField(default = timezone.now(), editable=False)
    user = models.ForeignKey(User, on_delete = models.SET_NULL, null=True)
    item = models.ForeignKey(Item, on_delete = models.SET_NULL, null=True, help_text='Select item')
    received_quantity = models.IntegerField(help_text='Enter received quantity')
    cost_price = models.FloatField(help_text='Enter cost price')
    price_per_piece = models.FloatField(help_text='Enter price of single piece')

    class Meta:
        verbose_name_plural = "Received items"

    def __str__(self):
        # return f'{self.received_quantity} ({self.item.item_name})'
        return f'{self.item.item_name}'
    
    def get_absolute_url(self):
        return reverse('received_item-detail', args=[str(self.id)])

class Sold_item(models.Model):
    # solgt_id = models.AutoField(primary_key = True)
    timestamp = models.DateTimeField(default = timezone.now(), editable=False)
    user = models.ForeignKey(User, on_delete = models.SET_NULL, null=True)
    item = models.ForeignKey(Item, on_delete = models.CASCADE, help_text='Select item')
    #item = models.ForeignKey(Item, on_delete = models.SET_NULL, null=True, help_text='Select item')
    sold_quantity = models.IntegerField(help_text='Enter sold quantity')

    class Meta:
        verbose_name_plural = "Sold items"

    def __str__(self):
        return f'{self.item.item_name}'
    
    def get_absolute_url(self):
        return reverse('sold_item-detail', args=[str(self.id)])

kioskapp/views.py
from django.shortcuts import get_object_or_404, render
from .models import User, User_type, Supplier, Received_item, Sold_item, Item_batch, Item_properties, Item, Category
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

# Create your views here.
# @login_required
def index(request):
    """View function for home page of site."""

    # Generate counts of some objects
    # num_items, num_categories, num_suppliers, num_receiveditems,
    # num_solditems, num_availableitems  
    num_items = Item.objects.all().count()
    num_categories = Category.objects.all().count()
    num_suppliers = Supplier.objects.all().count()
    num_receiveditems = Received_item.objects.all().count()
    # all() is implied by default
    num_solditems = Sold_item.objects.count()

    # Available items (change this. make it according to item name)
    num_availableitems = num_receiveditems - num_solditems

    context = {
        'num_items': num_items,
        'num_categories': num_categories,
        'num_suppliers': num_suppliers,
        'num_receiveditems': num_receiveditems,
        'num_solditems': num_solditems, 
        'num_availableitems': num_availableitems
    }

    # return render(request, 'index.html')
    return render(request, 'index.html', context=context)

class ItemsListView(generic.ListView):
    model = Item
    #allow_empty = False

class ItemDetailView(generic.DetailView):
    model = Item

# def item_list_view(request):
#     item = Item.objects.all()
#     return render(request, 'kioskapp/item_list.html', context={'item': item})

# def item_detail_view(request, primary_key):
#     item = get_object_or_404(Item, pk=primary_key)
#     return render(request, 'item_detail.html', context={'item': item})

class SuppliersListView(LoginRequiredMixin, generic.ListView):
    # login_url = '/login/'
    # redirect_field_name = 'redirect_to'
    model = Supplier

class SupplierDetailView(LoginRequiredMixin, generic.DetailView):
    model = Supplier

class CategoriesListView(generic.ListView):
    model = Category

class CategoryDetailView(generic.DetailView):
    model = Category

class ReceivedItemsListView(LoginRequiredMixin, generic.ListView):
    model = Received_item

class ReceivedItemDetailView(LoginRequiredMixin, generic.DetailView):
    model = Received_item

class SoldItemsListView(LoginRequiredMixin, generic.ListView):
    model = Sold_item

class SoldItemDetailView(LoginRequiredMixin, generic.DetailView):
    model = Sold_item

class ItemCreate(LoginRequiredMixin, CreateView):
    model = Item
    fields = '__all__'

class ItemUpdate(LoginRequiredMixin, UpdateView):
    model = Item
    fields = ['barcode', 'item_name', 'category', 'brandname', 'modelname', 'item_description', 'supplier', 'sellingprice']

class ItemDelete(LoginRequiredMixin, DeleteView):
    model = Item
    success_url = reverse_lazy('items')
    

kioskapp/templates/kioskapp/category_detail.html
{% extends "base_generic.html" %}

{% block title %} 
{{category.category_name}} Detail

{% endblock %}

{% load static %} 
<link rel="stylesheet" href="{% static 'css/styles.css' %}">

{% block content %}
    <h1>{{category.category_name}} Detail</h1>
    <br>

    <p><strong>By: </strong>{{category.user}},
    on {{category.timestamp}}</p>
    <hr>
    <!-- <p><strong>Category name: </strong>{{category.category_name}}</p> -->
    
    <p><strong>Category items: </strong>
    {% for item in category.item_set.all %}
        {% if not forloop.last %}
            {{item.item_name}},
        {% else %}
            {{item.item_name}}
        {% endif %}
    {% endfor %}
    </p>
{% endblock %}

kioskapp/templates/kioskapp/category_list.html
{% extends "base_generic.html" %}

{% block title %} 
Categories List
{% endblock %}

{% load static %} 
<link rel="stylesheet" href="{% static 'css/styles.css' %}">

{% block content %}
    <h1>Categories List</h1>

    {% if category_list %}
        <ul>
            {% for category in category_list %}
                <li>
                    <a href="{{ category.get_absolute_url }}">{{ category.category_name }}</a>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>There is no category of item in Kiosk.</p>
    {% endif %}
{% endblock %}

kioskapp/templates/kioskapp/item_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Item</h1>

<p>Are you sure you want to delete the item: {{ item }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>

{% endblock %}

kioskapp/templates/kioskapp/item_detail.html
{% extends "base_generic.html" %}

{% block title %} 
{{item.item_name}} Detail

{% endblock %}

{% load static %} 
<link rel="stylesheet" href="{% static 'css/styles.css' %}">

{% block content %}
    <h1>{{item.item_name}} Detail</h1>
    <br>

    <h2>{{item.item_name}} general information</h2>
    <p><strong>By: </strong>{{item.user}},
    on {{item.timestamp}}</p>
    <hr>
    <p><strong>Barcode: </strong>{{item.barcode}}</p>
    <p><strong>Category: </strong>{{item.category}}</p>
    <p><strong>Brand name: </strong>{{item.brandname}}</p>
    <p><strong>Model name: </strong>{{item.modelname}}</p>
    <p><strong>Item description: </strong>{{item.item_description}}</p>
    <p><strong>Supplier: </strong>{{item.supplier}}</p>
    <p><strong>Selling price: </strong>{{item.sellingprice}}</p>
    <br>

    <h2>{{item.item_name}} properties</h2>
    {% for properties in item.item_properties_set.all %}
        <hr>
        <p><strong>Color: </strong>{{properties.color}}</p>
        <p><strong>Size: </strong>{{properties.size}}</p>
        <p><strong>Weight: </strong>{{properties.weight}}</p>

    {% endfor %}
    <br>

    <h2>{{item.item_name}} batch information</h2>
    {% for batch in item.item_batch_set.all %}
        <hr>
        <p><strong>Batch code: </strong>{{batch.item_batch_code}}</p>
        <p><strong>Manufacture date: </strong>{{batch.manufacture_date}}</p>
        <p><strong>Expiry date: </strong>{{batch.expiry_date}}</p>

    {% endfor %}
{% endblock %}

kioskapp/templates/kioskapp/item_form.html
{% extends "base_generic.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

kioskapp/templates/kioskapp/item_list.html
{% extends "base_generic.html" %}

{% block title %} 
Items List
{% endblock %}

{% load static %} 
<link rel="stylesheet" href="{% static 'css/styles.css' %}">

{% block content %}
    <h1>Items List</h1>

    {% if item_list %}
        <ul>
            {% for item in item_list %}
                <li>
                    <a href="{{ item.get_absolute_url }}">{{ item.item_name }}</a>
                    ({{ item.brandname }}, {{item.modelname}}, kr. {{item.sellingprice}})
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>There is no item in Kiosk.</p>
    {% endif %}
{% endblock %}

kioskapp/templates/kioskapp/received_item_detail.html
{% extends "base_generic.html" %}

{% block title %} 
{{received_item.item.item_name}} Detail

{% endblock %}

{% load static %} 
<link rel="stylesheet" href="{% static 'css/styles.css' %}">

{% block content %}
    <h1>{{received_item.item.item_name}} Detail</h1>
    <br>

    <p><strong>By: </strong>{{received_item.user}},
    on {{received_item.timestamp}}</p>
    <hr>
    
    <p><strong>Quantity received: </strong>{{received_item.received_quantity}}</p>
    <p><strong>Total cost price: </strong>kr. {{received_item.cost_price}}</p>
    <p><strong>Price per piece: </strong>kr. {{received_item.price_per_piece}}</p>
{% endblock %}

kioskapp/templates/kioskapp/received_item_list.html
{% extends "base_generic.html" %}

{% block title %} 
Received Items List
{% endblock %}

{% load static %} 
<link rel="stylesheet" href="{% static 'css/styles.css' %}">

{% block content %}
    <h1>Received Items List</h1>

    {% if received_item_list %}
        <ul>
            {% for received_item in received_item_list %}
                <li>
                    <a href="{{ received_item.get_absolute_url }}">{{ received_item.item.item_name }}</a>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>There is no received item in Kiosk.</p>
    {% endif %}
{% endblock %}

kioskapp/templates/kioskapp/sold_item_detail.html
{% extends "base_generic.html" %}

{% block title %} 
{{sold_item.item.item_name}} Detail

{% endblock %}

{% load static %} 
<link rel="stylesheet" href="{% static 'css/styles.css' %}">

{% block content %}
    <h1>{{sold_item.item.item_name}} Detail</h1>
    <br>

    <p><strong>By: </strong>{{sold_item.user}},
    on {{sold_item.timestamp}}</p>
    <hr>
    
    <p><strong>Sold quantity: </strong>{{sold_item.sold_quantity}}<!--, 
    out of 
     {% for received_item in sold_item.received_item_set.all %}
        {{received_item.received_quantity}}
    {% endfor %}  -->
    </p>
{% endblock %}

kioskapp/templates/kioskapp/sold_item_list.html
{% extends "base_generic.html" %}

{% block title %} 
Sold Items List
{% endblock %}

{% load static %} 
<link rel="stylesheet" href="{% static 'css/styles.css' %}">

{% block content %}
    <h1>Sold Items List</h1>

    {% if sold_item_list %}
        <ul>
            {% for sold_item in sold_item_list %}
                <li>
                    <a href="{{ sold_item.get_absolute_url }}">{{ sold_item.item.item_name }}</a>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>There is no sold item in Kiosk.</p>
    {% endif %}
{% endblock %}

kioskapp/templates/kioskapp/supplier_detail.html
{% extends "base_generic.html" %}

{% block title %} 
{{supplier.supplier_name}} Detail

{% endblock %}

{% load static %} 
<link rel="stylesheet" href="{% static 'css/styles.css' %}">

{% block content %}
    <h1>{{supplier.supplier_name}} Detail</h1>
    <br>

    <p><strong>By: </strong>{{supplier.user}},
    on {{supplier.timestamp}}</p>
    <hr>
    <!-- <p><strong>Supplier name: </strong>{{supplier.supplier_name}}</p> -->
    
    <p><strong>Supplier items: </strong>
    {% for item in supplier.item_set.all %}
        <!-- {{item.item_name}} , -->
        {% if not forloop.last %}
            {{item.item_name}},
        {% else %}
            {{item.item_name}}
        {% endif %}
        <!-- {% if item.item_name.count >= 1 %}, {% else %}{% endif %}
        {{item.item_name.count}} -->
        
    {% endfor %}
    </p>
{% endblock %}

kioskapp/templates/kioskapp/supplier_list.html
{% extends "base_generic.html" %}

{% block title %} 
Suppliers List
{% endblock %}

{% load static %} 
<link rel="stylesheet" href="{% static 'css/styles.css' %}">

{% block content %}
    <h1>Suppliers List</h1>

    {% if supplier_list %}
        <ul>
            {% for supplier in supplier_list %}
                <li>
                    <a href="{{ supplier.get_absolute_url }}">{{ supplier.supplier_name }}</a>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>There is no supplier for Kiosk.</p>
    {% endif %}
{% endblock %}